<!-- 

var slideshow = new Array();
var currentPic = 0;
    slideshow[0] = new Array();
    slideshow[0]['src'] = "Pictures/ShadowLogoSep.jpg";
    slideshow[0]['href'] = "photo.php?ID_num=320";
    slideshow[1] = new Array();
    slideshow[1]['src'] = "Pictures/DivingBoard.jpg";
    slideshow[1]['href'] = "photo.php?ID_num=67";
    slideshow[2] = new Array();
    slideshow[2]['src'] = "Pictures/ReynoldsGoat.jpg";
    slideshow[2]['href'] = "photo.php?ID_num=5";
    slideshow[3] = new Array();
    slideshow[3]['src'] = "Pictures/AliceLake1.jpg";
    slideshow[3]['href'] = "photo.php?ID_num=17";
    slideshow[4] = new Array();
    slideshow[4]['src'] = "Pictures/SilverForestPrimal.jpg";
    slideshow[4]['href'] = "photo.php?ID_num=11";
    slideshow[5] = new Array();
    slideshow[5]['src'] = "Pictures/SnowshoesCenterville.jpg";
    slideshow[5]['href'] = "photo.php?ID_num=133";
    slideshow[6] = new Array();
    slideshow[6]['src'] = "Pictures/Sundance1.jpg";
    slideshow[6]['href'] = "photo.php?ID_num=16";
    slideshow[7] = new Array();
    slideshow[7]['src'] = "Pictures/UpperBells1.jpg";
    slideshow[7]['href'] = "photo.php?ID_num=139";
    slideshow[8] = new Array();
    slideshow[8]['src'] = "Pictures/BachsOrgan.jpg";
    slideshow[8]['href'] = "photo.php?ID_num=236";
    slideshow[9] = new Array();
    slideshow[9]['src'] = "Pictures/ThunderbirdGlacier.jpg";
    slideshow[9]['href'] = "photo.php?ID_num=422";
    slideshow[10] = new Array();
    slideshow[10]['src'] = "Pictures/BeachMounds.jpg";
    slideshow[10]['href'] = "photo.php?ID_num=360";
    slideshow[11] = new Array();
    slideshow[11]['src'] = "Pictures/moundshot1Titcomb.jpg";
    slideshow[11]['href'] = "photo.php?ID_num=517";
    slideshow[12] = new Array();
    slideshow[12]['src'] = "Pictures/SolDucForest.jpg";
    slideshow[12]['href'] = "photo.php?ID_num=33";
    slideshow[13] = new Array();
    slideshow[13]['src'] = "Pictures/DoughnutFallsWinter.jpg";
    slideshow[13]['href'] = "photo.php?ID_num=114";
    slideshow[14] = new Array();
    slideshow[14]['src'] = "Pictures/AntelopeCoyote.jpg";
    slideshow[14]['href'] = "photo.php?ID_num=268";
    slideshow[15] = new Array();
    slideshow[15]['src'] = "Pictures/BoxLakeReflect1.jpg";
    slideshow[15]['href'] = "photo.php?ID_num=89";
    slideshow[16] = new Array();
    slideshow[16]['src'] = "Pictures/GiantClaw.jpg";
    slideshow[16]['href'] = "photo.php?ID_num=285";
    slideshow[17] = new Array();
    slideshow[17]['src'] = "Pictures/FlamingTulips.jpg";
    slideshow[17]['href'] = "photo.php?ID_num=91";
    slideshow[18] = new Array();
    slideshow[18]['src'] = "Pictures/GNPPocketLake.jpg";
    slideshow[18]['href'] = "photo.php?ID_num=418";
    slideshow[19] = new Array();
    slideshow[19]['src'] = "Pictures/HellRoaringSunrise.jpg";
    slideshow[19]['href'] = "photo.php?ID_num=12";
    slideshow[20] = new Array();
    slideshow[20]['src'] = "Pictures/MonarchFlowerZoom.jpg";
    slideshow[20]['href'] = "photo.php?ID_num=288";
    slideshow[21] = new Array();
    slideshow[21]['src'] = "Pictures/VAFalls1.jpg";
    slideshow[21]['href'] = "photo.php?ID_num=335";
    slideshow[22] = new Array();
    slideshow[22]['src'] = "Pictures/SiyehSummit1.jpg";
    slideshow[22]['href'] = "photo.php?ID_num=428";
    slideshow[23] = new Array();
    slideshow[23]['src'] = "Pictures/SecretGarden3.jpg";
    slideshow[23]['href'] = "photo.php?ID_num=21";
    slideshow[24] = new Array();
    slideshow[24]['src'] = "Pictures/OregonBeach1.jpg";
    slideshow[24]['href'] = "photo.php?ID_num=189";
    slideshow[25] = new Array();
    slideshow[25]['src'] = "Pictures/Antelope1.jpg";
    slideshow[25]['href'] = "photo.php?ID_num=264";
    slideshow[26] = new Array();
    slideshow[26]['src'] = "Pictures/OverhangTowerFlowers.jpg";
    slideshow[26]['href'] = "photo.php?ID_num=369";
    slideshow[27] = new Array();
    slideshow[27]['src'] = "Pictures/BlancheFoliage2.jpg";
    slideshow[27]['href'] = "photo.php?ID_num=59";
    slideshow[28] = new Array();
    slideshow[28]['src'] = "Pictures/AbacusIce.jpg";
    slideshow[28]['href'] = "photo.php?ID_num=60";
    slideshow[29] = new Array();
    slideshow[29]['src'] = "Pictures/ShadowDeathNegTxt.jpg";
    slideshow[29]['href'] = "photo.php?ID_num=317";

  function SlideshowLaunch() {
    if (currentPic == 29)
       currentPic =0;
    else
       ++currentPic;
    document.images[1].src = slideshow[currentPic]['src'];
    document.getElementById('slideshowLink').href = slideshow[currentPic]['href'];
  }

-->
